name: ndp.py test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.extras.txt
          pip install .

      - name: Run NDP demo/test scripts
        run: |
          python examples/ndp/1.query_artifacts.py --verbose
          python examples/ndp/2.process.py --verbose
          python examples/ndp/3.query.py --verbose
          python examples/ndp/4.find.py --verbose
          python examples/ndp/5.inspect.py --verbose
          python examples/ndp/6.validate.py --verbose
          python examples/ndp/7.notebook.py --verbose
          python examples/ndp/8.close.py --verbose

      - name: Run NDP pytest
        run: |
          pip install pytest
          pytest dsi/backends/tests/test_ndp.py