name: sqlite.py test

on:
  push:
    branches:
    - gh-pages


jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install gitpython
        python -m pip install pyyaml
    - name: Test reader
      run: |
        pip install pytest
        pytest dsi/backends/tests/test_sqlite.py



